GET http://localhost:8081/api/v1/region
Content-Type: application/json
ACCESS_TOKEN: {{token}}

###

POST http://localhost:8081/api/v1/region
Content-Type: application/json
ACCESS_TOKEN: {{token}}

{
  "name": "WestJapan",
  "comment": "西日本"
}

###

GET http://localhost:8081/api/v1/region
Content-Type: application/json
ACCESS_TOKEN: {{token}}
